variables:
  _USER: "builduser"
  _PATH: /home/$_USER/$CI_PROJECT_NAME

stages:
  - build

build-deb-32:
  image: migasfree/deb-ci:32
  stage: build
  script:
    - useradd -m $_USER
    - mkdir -p $_PATH
    - mv * $_PATH
    - pushd $_PATH/bin
    - su -c "./create-package" $_USER
    - popd
    - mv $_PATH/deb_dist/*.deb .
  artifacts:
    expire_in: 1 days
    paths:
      - ./*.deb
  only:
    - tags

build-deb-64:
  image: migasfree/deb-ci:64
  stage: build
  script:
    - useradd -m $_USER
    - mkdir -p $_PATH
    - mv * $_PATH
    - pushd $_PATH/bin
    - su -c "./create-package" $_USER
    - popd
    - mv $_PATH/deb_dist/*.deb .
  artifacts:
    expire_in: 1 days
    paths:
      - ./*.deb
  only:
    - tags

build-rpm-64:
  image: migasfree/rpm-ci:64
  stage: build
  script:
    - useradd -m $_USER
    - mkdir -p $_PATH
    - mv * $_PATH
    - pushd $_PATH/bin
    - su -c "./create-package" $_USER
    - popd
    - mv $_PATH/dist/*.rpm .
  artifacts:
    expire_in: 1 days
    paths:
      - ./*.rpm
  only:
    - tags
